version: '3.8'

services:
  # nmw-front:
  #   build:
  #     context: front
  #     dockerfile: Dockerfile
  #   container_name: nmw-front
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     NEXT_PUBLIC_API_URL: "http://localhost:1000/"
  #     NEXT_PUBLIC_NOMOREWASTEUSER: "NOMOREWASTEUSER"
  #     NEXT_PUBLIC_TOKEN: "NOMOREWASTETOKEN"
  #   depends_on:
  #     - no-more-waste-bdd
  #   networks:
  #     - nmw-network

  php-apache:
    build: ./htdocs
    ports:
      - "1000:8000"
    volumes:
      - ./htdocs:/var/www/html
    restart: always
    depends_on:
      - no-more-waste-bdd
    networks:
      - nmw-network

  no-more-waste-bdd:
    image: mysql:8.0
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nomorewaste
    ports:
      - "3306:3306"
    restart: always
    networks:
      - nmw-network

volumes:
  nmw-postgres-data:

networks:
  nmw-network: