CREATE TABLE `Pays` (
	`Nom` VARCHAR(255) UNIQUE,
	PRIMARY KEY(`Nom`)
);


CREATE TABLE `Ville` (
	`Pays` VARCHAR(255),
	`Nom` VARCHAR(255) UNIQUE,
	`Adresse` VARCHAR(255),
	PRIMARY KEY(`Nom`)
);


CREATE TABLE `Entrepot` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`ville` VARCHAR(255),
	`latitude` FLOAT,
	`longitude` FLOAT,
	PRIMARY KEY(`id`)
);


CREATE TABLE `Adherent` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`Password` VARCHAR(255),
	`Abonnement` VARCHAR(255),
	`Prenom` VARCHAR(255),
	`Nom` VARCHAR(255),
	`Mail` VARCHAR(255),
	`Ville` VARCHAR(255),
	`Service` VARCHAR(255),
	`token` VARCHAR(255),
	PRIMARY KEY(`id`)
);


CREATE TABLE `Commercant` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`Nom` VARCHAR(255) NOT NULL,
	`Adresse` VARCHAR(255) NOT NULL,
	`Referent` INTEGER NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE `Abonnement` (
	`Nom` VARCHAR(255) UNIQUE,
	`PrixMois` INTEGER,
	`PrixAn` INTEGER,
	`Description` VARCHAR(255),
	PRIMARY KEY(`Nom`)
);


CREATE TABLE `Perks` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`Nom` VARCHAR(255),
	`Abonnement` VARCHAR(255),
	PRIMARY KEY(`id`)
);


CREATE TABLE `Stock` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`Entrepot` INTEGER,
	`Item` VARCHAR(255),
	`Quantité` INTEGER,
	PRIMARY KEY(`id`)
);


CREATE TABLE `Livraison` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`Collecte` DATETIME,
	`Entrepot` INTEGER,
	`Statut` VARCHAR(255),
	`Adresse` VARCHAR(255),
	PRIMARY KEY(`id`)
);


CREATE TABLE `Error` (
	`id` INTEGER NOT NULL UNIQUE,
	`Titre` VARCHAR(255),
	`texte` VARCHAR(255),
	PRIMARY KEY(`id`)
);


CREATE TABLE `Ticket` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`Titre` VARCHAR(255),
	`Statut` VARCHAR(255),
	`Tag` VARCHAR(255),
	`Priority` VARCHAR(255),
	PRIMARY KEY(`id`)
);


CREATE TABLE `Palette` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Livraison` INTEGER,
	`Stock` INTEGER,
	`Quantité` INTEGER,
	PRIMARY KEY(`id`)
);